package enums;

public enum TipoRetorno {
	URL, 
	MASSA,
	CORPO, 
	STATUS, 
	NOMEAPK, 
	DEVICEID, 
	VERSAODOSO, 
	DEVICENAME,
	SYSTEMPORT,
	PACOTESTEPS,
	APPWAITACTIVITY, 
	CAMINHODASFEATURES,
	CAMINHOARQUIVORELATORIOXML,
	CAMINHOARQUIVORELATORIOJSON;
}